pilagod/waallet-extension

- config/test/index.ts
> Update the SimpleAccount for test

- demo.md
- Resolves #25
1. Swap ETH for UNI tokens in AA contract on Sepolia testnet within Uniswap DApp.
2. Transfer with SimpleAccount on Local Testnet.
3. Transfer with PasskeyAccount on Local Testnet.
- [https://github.com/pilagod/waallet-extension/blob/add-demo-md/demo.md](https://github.com/pilagod/waallet-extension/blob/add-demo-md/demo.md)
> doc: Added current results demo and reproduction process markdown

- config/test/index.ts
- packages/provider/waallet/background/provider.ts
- Resolves pilagod/waallet-contract#8
- Resolves #27
- waallet-contract: [https://github.com/pilagod/waallet-contract/pull/10](https://github.com/pilagod/waallet-contract/pull/10)
1. Due to the removal of custom compiler parameters (optimizer_runs = 999999, via_ir = true) in waallet-contract, the contract addresses used in the tests need to be modified.
> feat: Update addresses for SimpleAccount and PasskeyAccount in the test

- package-lock.json
- package.json
- packages/webAuthn/background/webAuthn.ts
- Resolves #30
1. Set a sufficiently large window size for testing.
> refac: Adject window size for testing

- README.md
- demo.md
1. add passkey demo in demo.md
2. change the demo video in REACME.md
- [demo link](https://github.com/pilagod/waallet-extension/blob/add-passkey-demo/demo.md#demo-2-swap-eth-for-uni-tokens-with-passkey-verification-in-the-aa-contract-on-the-sepolia-testnet-within-the-uniswap-dapp)
- [README link](https://github.com/pilagod/waallet-extension/blob/add-passkey-demo/README.md)
> doc: add passkey demo

- config/test/index.ts
- packages/account/PasskeyAccount/index.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/index.ts
- packages/provider/bundler/index.ts
- packages/provider/waallet/background/provider.ts
To let tests pass, it requires settings in https://github.com/pilagod/waallet-contract/pull/20
> Add verifying paymaster

- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/index.ts
- packages/provider/waallet/background/provider.ts
- tabs/userOperationAuthorization.tsx
> Remove option on paymaster interface

- packages/paymaster/NullPaymaster/index.ts
- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/index.ts
- packages/token/index.ts
- tabs/userOperationAuthorization.tsx
> Quote fee from paymaster

- popup/index.tsx
- popup/pages/info.tsx
- popup/pages/send.tsx
- popup/util/page.ts
> Popup send eth

- background/index.ts
- background/messages/storage.ts
- background/storage.ts
- package-lock.json
- package.json
- packages/util/address/index.ts
- popup/component/navbar.tsx
- popup/context/provider.tsx
- popup/ctx/provider.tsx
- popup/index.tsx
- popup/pages/info.tsx
- popup/pages/send.tsx
- popup/storage/index.ts
* Add Navbar to show chain id and account address
* Refactor pages with storage hooks
> Add Navbar

- background/provider.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/util/testing/suite/waallet.ts
- packages/waallet/background/pool/userOperation/index.ts
- packages/waallet/background/pool/userOperation/sender.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
This PR is based on #73 
* Extract `UserOperationPool` interface
> Add userop pool

- background/index.ts
- background/manager.ts
- background/provider.ts
- config/test/index.ts
- config/test/manager.ts
- packages/account/PasskeyAccount/index.test.ts
- packages/bundler/provider.ts
- packages/network/index.ts
- packages/network/manager.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/rpc/json/provider.ts
- packages/util/testing/suite/account.ts
- packages/util/testing/suite/waallet.ts
- packages/waallet/background/pool/userOperation/index.ts
- packages/waallet/background/pool/userOperation/sender.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
This PR is based on #74 
* Add network manager to manage network in single place
* Integrate network manager for components
> Add network manager

- background/manager.ts
- background/provider.ts
- packages/account/manager/index.ts
- packages/account/manager/single.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/util/testing/suite/account.ts
- packages/util/testing/suite/waallet.ts
- packages/waallet/background/pool/userOperation/index.ts
- packages/waallet/background/pool/userOperation/sender.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
This PR is based on #76 
* Use sender id in user operation pool
> use sender id in userop pool

- background/pool.ts
- background/storage.ts
- packages/bundler/index.ts
- packages/storage/observable.test.ts
- packages/storage/observable.ts
- packages/waallet/background/pool/userOperation/index.ts
- packages/waallet/background/pool/userOperation/sender.ts
- packages/waallet/background/provider.ts
This PR is based on #78
* Refactor `ObservableStorage` to allow subscribing to specific fields
* Add immer updater pattern to `ObservableStorage` for setting state
* Add user operation storage pool
> Add userop storage pool

- app/page/info.tsx
- background/index.ts
- background/pool.ts
- background/storage/local.ts
1. Add creation and block timestamp in UserOpLog type.
2. Add userOp history timestamp in Popup Script.
([Video link](https://youtu.be/CWNYUvl0KZM))
> Add creation and block timestamp in UserOpLog type

- app/component/navbar.tsx
- app/storage/index.ts
This PR is based on #98 
* Enable switch account feature on Navbar
> Add switch account

- app/component/navbar.tsx
- app/index.tsx
- app/page/info.tsx
- app/storage/index.ts
- background/index.ts
- background/storage/local.ts
- config/index.ts
To test this PR, some actions require to setup
* Comment out account information in `.env` file
* Open extension service worker, and type `chrome.storage.local.clear()` in the console to clear all data in storage.
> Create first account

- app/page/authorization/userOperation.tsx
- app/storage/index.ts
- background/index.ts
- background/messages/storage.ts
- background/pool.ts
- storage/local/index.ts
This PR is based on #111 
* Move user op from pending logs into account logs when its status goes away from pending.
> Refine userop pool

- app/page/info/index.tsx
- app/page/info/tokens.tsx
- app/storage/index.ts
- packages/network/util/index.ts
- storage/local/index.ts
1. Display initial ETH token
2. Detect and prevent importing duplicate token
3. Add TokenInfoModal page for exploring, updating, and removing tokens.
4. Refresh every 3.33 seconds to check for balance updates of all tokens under this account.
([Link](https://youtu.be/eQB_gQQthPs))
1. Token transaction
> Token init and import prevent

- app/page/info/index.tsx
- app/page/info/tokens.tsx
- background/index.ts
1. Update token every 3 seconds.
2. Remove the update function from info and token pages.
3. Reduce imported packages.
> refac: Move token update to background

- app/page/authorization/userOperation.tsx
- packages/account/PasskeyAccount/index.test.ts
- packages/account/PasskeyAccount/index.ts
- packages/account/SimpleAccount/index.ts
- packages/account/index.ts
- packages/account/skeleton.ts
- packages/node/index.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/index.ts
- packages/util/testing/suite/waallet.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
- storage/local/manager.ts
This PR is based on #119 
* Setup runner in account and paymaster constructor
> Refine account and paymaster

- app/page/authorization/userOperation.tsx
- packages/account/PasskeyAccount/factory.ts
- packages/account/PasskeyAccount/index.ts
- packages/account/SimpleAccount/factory.ts
- packages/account/SimpleAccount/index.ts
- packages/account/factory.ts
- packages/account/index.ts
- packages/account/skeleton.ts
- packages/bundler/provider.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
- packages/waallet/rpc.ts
This PR is based on #121 
* Use EntryPoint address on account to send or estimate user operation.
> Refine account entry point usage

- app/index.tsx
- app/page/authorization/userOperation.tsx
- app/page/info/activity.tsx
- app/storage/index.ts
- background/index.ts
- background/pool.ts
- background/provider.ts
- packages/bundler/index.ts
- packages/bundler/provider.ts
- packages/paymaster/NullPaymaster/index.ts
- packages/paymaster/VerifyingPaymaster/index.test.ts
- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/index.ts
- packages/util/testing/suite/account.ts
- packages/util/testing/suite/waallet.ts
- packages/waallet/background/pool/transaction/index.ts
- packages/waallet/background/pool/transaction/sender.ts
- packages/waallet/background/pool/userOperation/index.ts
- packages/waallet/background/pool/userOperation/sender.ts
- packages/waallet/background/provider.test.ts
- packages/waallet/background/provider.ts
- storage/local/index.ts
This PR is based on #122 
> [!NOTE]
> Require to clear storage.
* Make transaction pool be able to accept multiple types of transaction, ERC4337v06 (a.k.a UserOperation for v0.6) is just one of them.
> Refine log by tx

- app/page/info/tokens.tsx
- app/page/send.tsx
- packages/network/util/index.ts
- packages/util/number/index.ts
([Video](https://youtu.be/ICW6kxak9nk))
> Send token in Send page

- app/page/info/tokens.tsx
- packages/network/util/index.ts
([Video](https://youtu.be/UMAkaOx4-KU))
> Send token in token modal

- app/page/info/tokens.tsx
- Base on #128
- Add the link on Native token in token modal
> Add the link on Native token in token modal

- config/test/index.ts
- packages/bundler/userOperation/v0_7.ts
- packages/paymaster/VerifyingPaymaster/index.ts
- packages/paymaster/VerifyingPaymaster/index.v0_6.test.ts
- packages/paymaster/VerifyingPaymaster/index.v0_7.test.ts
- packages/paymaster/index.ts
- packages/util/testing/suite/waallet.ts
This PR is stacked on #131, and also depends on https://github.com/pilagod/waallet-contract/pull/40
> Verifying paymaster 0.7

- app/hook/storage.ts
- app/page/home/index.tsx
- app/page/home/navbar.tsx
- app/storage/slice/account.ts
- storage/local/index.ts
- storage/local/state.ts
* Add id to account & network in storage
* Refine storage hooks
> Refine storage id

- app/page/send/index.tsx
- Based on #172 
- Add markup for Send Amount
- Implement set Max value for amount
- Integrate the previous codebase's `sendNativeToken`, `sendErc20Token`, and `handleSend` functions. ([ref](https://github.com/pilagod/waallet-extension/blob/c7dcf5e3bf182c900db689a974a649384985203b/app/page/send.tsx#L63-L69).)
https://github.com/user-attachments/assets/1f4b8966-7f0f-43a2-ba32-329150920349
> Refine Send amount

- config/test/index.ts
An attempt to fix irregularly CI errors.
> Wrap nonce manager

- app/index.tsx
Current situation is that when review page is opened by DApp, it would be placed on the top-left corner of a bigger page. This PR make app horizontal center in big window.
> Horizontal center app

- README.md
Shared from @pilagod's recorded demo video:
[![Waallet Demo](https://i.imgur.com/ojApmiQ.gif)](https://youtu.be/9D5K4IlofLY)
> doc: Update the demo image in README.md

- config/development/index.ts
Update passkey factory to resolve this issue
> Fix invalid signature error

- app/storage/index.ts
- app/storage/middleware/background.ts
- package-lock.json
- package.json
Make app wait for background storage syncing back the state update.
> Fix background middleware

- app/hook/storage.ts
- app/index.tsx
- app/page/review/index.tsx
- app/page/review/transaction.tsx
- app/storage/slice/transaction.ts
- background/index.ts
- background/pool.ts
- storage/local/actor.ts
- storage/local/index.ts
- storage/local/state.ts
* Restruct `pendingTransaction` to `pendingRequests`
* Will add a new request type `EIP712` in the upcoming PR.
> [EIP-712] Restruct pending requests
